name: Waypoint

on:
  workflow_call:
    inputs:
      operation:
        description: Waypoint operation to execute. Allowed values are up, destroy. Default to up.
        type: string
        default: up
      environment:
        required: true
        type: string
      workspace:
        required: true
        type: string
      tag:
        required: true
        type: string
      helm_dir:
        required: false
        type: string
    secrets:
      token:
        required: true
      kubeconfig:
        required: true
      WAYPOINT_SERVER_TOKEN:
        required: true
      WAYPOINT_SERVER_ADDR:
        required: true
      WAYPOINT_SERVER_TLS:
        required: false
      WAYPOINT_SERVER_TLS_SKIP_VERIFY:
        required: false
      WP_VARS_HCL:
        required: false


jobs:
  waypoint:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.waypoint.outputs.ingress_host }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: run - install dependencies
        run: |
          sudo apt-get install apt-transport-https --yes
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo dd status=none of=/usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt update && sudo apt install waypoint helm

      - name: docker - login container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.token }}

      - name: checkout
        uses: actions/checkout@v3

      - name: base64-to-file - KUBECONFIG
        id: kubeconfig
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'config'
          encodedString: ${{ secrets.kubeconfig }}

      - name: script - helm dependency update
        if: inputs.helm_dir
        run: |
          helm dependency update ${{ inputs.helm_dir }}

      - name: run - waypoint
        id: waypoint
        env:
          KUBECONFIG: ${{ steps.kubeconfig.outputs.filePath }}
          WAYPOINT_SERVER_TOKEN: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
          WAYPOINT_SERVER_ADDR: ${{ secrets.WAYPOINT_SERVER_ADDR }}
          WAYPOINT_SERVER_TLS: ${{ secrets.WAYPOINT_SERVER_TLS }}
          WAYPOINT_SERVER_TLS_SKIP_VERIFY: ${{ secrets.WAYPOINT_SERVER_TLS_SKIP_VERIFY }}
          WP_VAR_registry_auth_password: ${{ secrets.token }}
          WP_VAR_registry_auth_username: ${{ github.actor }}
          WP_VAR_registry_image_tag: ${{ inputs.tag }}
          WP_VARS_HCL: ${{ secrets.WP_VARS_HCL }}
        run: |
          waypoint init -plain
          waypoint ${{ inputs.operation }} -plain \
            -w ${{ inputs.workspace }} \
            ${{ inputs.operation == 'delete' && '-auto-approve' || '-prune-retain=2' }} \
            -var-file=<(printenv WP_VARS_HCL)

            echo "::set-output name=ingress_host::$(<ingress_host.wpoutput)"
